//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raverus.FiskalizacijaDEV.EXE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CisUrl {
            get {
                return ((string)(this["CisUrl"]));
            }
            set {
                this["CisUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TimeOut {
            get {
                return ((int)(this["TimeOut"]));
            }
            set {
                this["TimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RacunZahtjevDatoteka {
            get {
                return ((string)(this["RacunZahtjevDatoteka"]));
            }
            set {
                this["RacunZahtjevDatoteka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PoslovniProstorZahtjevDatoteka {
            get {
                return ((string)(this["PoslovniProstorZahtjevDatoteka"]));
            }
            set {
                this["PoslovniProstorZahtjevDatoteka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RacunOdgovorDatoteka {
            get {
                return ((string)(this["RacunOdgovorDatoteka"]));
            }
            set {
                this["RacunOdgovorDatoteka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PoslovniProstorOdgovorDatoteka {
            get {
                return ((string)(this["PoslovniProstorOdgovorDatoteka"]));
            }
            set {
                this["PoslovniProstorOdgovorDatoteka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NazivCertifikata {
            get {
                return ((string)(this["NazivCertifikata"]));
            }
            set {
                this["NazivCertifikata"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RacunZahtjevPotpisiDatoteka {
            get {
                return ((string)(this["RacunZahtjevPotpisiDatoteka"]));
            }
            set {
                this["RacunZahtjevPotpisiDatoteka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PoslovniProstorZahtjevPotpisiDatoteka {
            get {
                return ((string)(this["PoslovniProstorZahtjevPotpisiDatoteka"]));
            }
            set {
                this["PoslovniProstorZahtjevPotpisiDatoteka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RacunZahtjevPosaljiDatoteka {
            get {
                return ((string)(this["RacunZahtjevPosaljiDatoteka"]));
            }
            set {
                this["RacunZahtjevPosaljiDatoteka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PoslovniProstorZahtjevPosaljiDatoteka {
            get {
                return ((string)(this["PoslovniProstorZahtjevPosaljiDatoteka"]));
            }
            set {
                this["PoslovniProstorZahtjevPosaljiDatoteka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RacunOdgovorPotpisiDatoteka {
            get {
                return ((string)(this["RacunOdgovorPotpisiDatoteka"]));
            }
            set {
                this["RacunOdgovorPotpisiDatoteka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PoslovniProstorOdgovorPotpisiDatoteka {
            get {
                return ((string)(this["PoslovniProstorOdgovorPotpisiDatoteka"]));
            }
            set {
                this["PoslovniProstorOdgovorPotpisiDatoteka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RacunOdgovorPosaljiDatoteka {
            get {
                return ((string)(this["RacunOdgovorPosaljiDatoteka"]));
            }
            set {
                this["RacunOdgovorPosaljiDatoteka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PoslovniProstorOdgovorPosaljiDatoteka {
            get {
                return ((string)(this["PoslovniProstorOdgovorPosaljiDatoteka"]));
            }
            set {
                this["PoslovniProstorOdgovorPosaljiDatoteka"] = value;
            }
        }
    }
}
