//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Raverus.FiskalizacijaDEV.ConnectionTest.ConnectionTest {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConnectionTestSoap", Namespace="http://tempuri.org/")]
    public partial class ConnectionTest : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DohvatiListuMjestaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DohvatiListuInternetProvideraOperationCompleted;
        
        private System.Threading.SendOrPostCallback DohvatiListuTipVezeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DohvatiListuOsOperationCompleted;
        
        private System.Threading.SendOrPostCallback PosaljiOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConnectionTest() {
            this.Url = global::Raverus.FiskalizacijaDEV.ConnectionTest.Properties.Settings.Default.Raverus_FiskalizacijaDEV_ConnectionTest_ConnectionTest_ConnectionTest;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DohvatiListuMjestaCompletedEventHandler DohvatiListuMjestaCompleted;
        
        /// <remarks/>
        public event DohvatiListuInternetProvideraCompletedEventHandler DohvatiListuInternetProvideraCompleted;
        
        /// <remarks/>
        public event DohvatiListuTipVezeCompletedEventHandler DohvatiListuTipVezeCompleted;
        
        /// <remarks/>
        public event DohvatiListuOsCompletedEventHandler DohvatiListuOsCompleted;
        
        /// <remarks/>
        public event PosaljiCompletedEventHandler PosaljiCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DohvatiListuMjesta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DohvatiListuMjesta() {
            object[] results = this.Invoke("DohvatiListuMjesta", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DohvatiListuMjestaAsync() {
            this.DohvatiListuMjestaAsync(null);
        }
        
        /// <remarks/>
        public void DohvatiListuMjestaAsync(object userState) {
            if ((this.DohvatiListuMjestaOperationCompleted == null)) {
                this.DohvatiListuMjestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDohvatiListuMjestaOperationCompleted);
            }
            this.InvokeAsync("DohvatiListuMjesta", new object[0], this.DohvatiListuMjestaOperationCompleted, userState);
        }
        
        private void OnDohvatiListuMjestaOperationCompleted(object arg) {
            if ((this.DohvatiListuMjestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DohvatiListuMjestaCompleted(this, new DohvatiListuMjestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DohvatiListuInternetProvidera", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DohvatiListuInternetProvidera() {
            object[] results = this.Invoke("DohvatiListuInternetProvidera", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DohvatiListuInternetProvideraAsync() {
            this.DohvatiListuInternetProvideraAsync(null);
        }
        
        /// <remarks/>
        public void DohvatiListuInternetProvideraAsync(object userState) {
            if ((this.DohvatiListuInternetProvideraOperationCompleted == null)) {
                this.DohvatiListuInternetProvideraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDohvatiListuInternetProvideraOperationCompleted);
            }
            this.InvokeAsync("DohvatiListuInternetProvidera", new object[0], this.DohvatiListuInternetProvideraOperationCompleted, userState);
        }
        
        private void OnDohvatiListuInternetProvideraOperationCompleted(object arg) {
            if ((this.DohvatiListuInternetProvideraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DohvatiListuInternetProvideraCompleted(this, new DohvatiListuInternetProvideraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DohvatiListuTipVeze", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DohvatiListuTipVeze() {
            object[] results = this.Invoke("DohvatiListuTipVeze", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DohvatiListuTipVezeAsync() {
            this.DohvatiListuTipVezeAsync(null);
        }
        
        /// <remarks/>
        public void DohvatiListuTipVezeAsync(object userState) {
            if ((this.DohvatiListuTipVezeOperationCompleted == null)) {
                this.DohvatiListuTipVezeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDohvatiListuTipVezeOperationCompleted);
            }
            this.InvokeAsync("DohvatiListuTipVeze", new object[0], this.DohvatiListuTipVezeOperationCompleted, userState);
        }
        
        private void OnDohvatiListuTipVezeOperationCompleted(object arg) {
            if ((this.DohvatiListuTipVezeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DohvatiListuTipVezeCompleted(this, new DohvatiListuTipVezeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DohvatiListuOs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DohvatiListuOs() {
            object[] results = this.Invoke("DohvatiListuOs", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DohvatiListuOsAsync() {
            this.DohvatiListuOsAsync(null);
        }
        
        /// <remarks/>
        public void DohvatiListuOsAsync(object userState) {
            if ((this.DohvatiListuOsOperationCompleted == null)) {
                this.DohvatiListuOsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDohvatiListuOsOperationCompleted);
            }
            this.InvokeAsync("DohvatiListuOs", new object[0], this.DohvatiListuOsOperationCompleted, userState);
        }
        
        private void OnDohvatiListuOsOperationCompleted(object arg) {
            if ((this.DohvatiListuOsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DohvatiListuOsCompleted(this, new DohvatiListuOsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Posalji", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Posalji(System.Data.DataSet ds) {
            object[] results = this.Invoke("Posalji", new object[] {
                        ds});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PosaljiAsync(System.Data.DataSet ds) {
            this.PosaljiAsync(ds, null);
        }
        
        /// <remarks/>
        public void PosaljiAsync(System.Data.DataSet ds, object userState) {
            if ((this.PosaljiOperationCompleted == null)) {
                this.PosaljiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPosaljiOperationCompleted);
            }
            this.InvokeAsync("Posalji", new object[] {
                        ds}, this.PosaljiOperationCompleted, userState);
        }
        
        private void OnPosaljiOperationCompleted(object arg) {
            if ((this.PosaljiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PosaljiCompleted(this, new PosaljiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DohvatiListuMjestaCompletedEventHandler(object sender, DohvatiListuMjestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DohvatiListuMjestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DohvatiListuMjestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DohvatiListuInternetProvideraCompletedEventHandler(object sender, DohvatiListuInternetProvideraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DohvatiListuInternetProvideraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DohvatiListuInternetProvideraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DohvatiListuTipVezeCompletedEventHandler(object sender, DohvatiListuTipVezeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DohvatiListuTipVezeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DohvatiListuTipVezeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DohvatiListuOsCompletedEventHandler(object sender, DohvatiListuOsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DohvatiListuOsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DohvatiListuOsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PosaljiCompletedEventHandler(object sender, PosaljiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PosaljiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PosaljiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591