// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>Raverus.FiskalizacijaDEV.Schema</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>True</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>True</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>True</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>True</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Raverus.FiskalizacijaDEV.Schema
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Xml;
    using System.Collections.Generic;


    #region Base entity class
    public partial class EntityBase<T>
    {

        private static System.Xml.Serialization.XmlSerializer serializer;

        private static System.Xml.Serialization.XmlSerializer Serializer
        {
            get
            {
                if ((serializer == null))
                {
                    serializer = new System.Xml.Serialization.XmlSerializer(typeof(T));
                }
                return serializer;
            }
        }

        #region Serialize/Deserialize
        /// <summary>
        /// Serializes current EntityBase object into an XML document
        /// </summary>
        /// <returns>string XML value</returns>
        public virtual string Serialize(System.Text.Encoding encoding)
        {
            System.IO.StreamReader streamReader = null;
            System.IO.MemoryStream memoryStream = null;
            try
            {
                memoryStream = new System.IO.MemoryStream();
                System.Xml.XmlWriterSettings xmlWriterSettings = new System.Xml.XmlWriterSettings();
                xmlWriterSettings.Encoding = encoding;
                System.Xml.XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);

                System.Xml.Serialization.XmlSerializerNamespaces ns = new System.Xml.Serialization.XmlSerializerNamespaces();
                ns.Add("tns", "http://www.apis-it.hr/fin/2012/types/f73");
                ns.Add("xsi", "http://www.w3.org/2001/XMLSchema-instance");
                Serializer.Serialize(xmlWriter, this, ns);

                //Serializer.Serialize(xmlWriter, this);
                memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
                streamReader = new System.IO.StreamReader(memoryStream);
                return streamReader.ReadToEnd();
            }
            finally
            {
                if ((streamReader != null))
                {
                    streamReader.Dispose();
                }
                if ((memoryStream != null))
                {
                    memoryStream.Dispose();
                }
            }
        }

        public virtual string Serialize()
        {
            return Serialize(Encoding.UTF8);
        }

        /// <summary>
        /// Deserializes workflow markup into an EntityBase object
        /// </summary>
        /// <param name="xml">string workflow markup to deserialize</param>
        /// <param name="obj">Output EntityBase object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool Deserialize(string xml, out T obj, out System.Exception exception)
        {
            exception = null;
            obj = default(T);
            try
            {
                obj = Deserialize(xml);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool Deserialize(string xml, out T obj)
        {
            System.Exception exception = null;
            return Deserialize(xml, out obj, out exception);
        }

        public static T Deserialize(string xml)
        {
            System.IO.StringReader stringReader = null;
            try
            {
                stringReader = new System.IO.StringReader(xml);
                return ((T)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
            }
            finally
            {
                if ((stringReader != null))
                {
                    stringReader.Dispose();
                }
            }
        }

        /// <summary>
        /// Serializes current EntityBase object into file
        /// </summary>
        /// <param name="fileName">full path of outupt xml file</param>
        /// <param name="exception">output Exception value if failed</param>
        /// <returns>true if can serialize and save into file; otherwise, false</returns>
        public virtual bool SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
        {
            exception = null;
            try
            {
                SaveToFile(fileName, encoding);
                return true;
            }
            catch (System.Exception e)
            {
                exception = e;
                return false;
            }
        }

        public virtual bool SaveToFile(string fileName, out System.Exception exception)
        {
            return SaveToFile(fileName, Encoding.UTF8, out exception);
        }

        public virtual void SaveToFile(string fileName)
        {
            SaveToFile(fileName, Encoding.UTF8);
        }

        public virtual void SaveToFile(string fileName, System.Text.Encoding encoding)
        {
            System.IO.StreamWriter streamWriter = null;
            try
            {
                string xmlString = Serialize(encoding);
                streamWriter = new System.IO.StreamWriter(fileName, false, Encoding.UTF8);
                streamWriter.WriteLine(xmlString);
                streamWriter.Close();
            }
            finally
            {
                if ((streamWriter != null))
                {
                    streamWriter.Dispose();
                }
            }
        }

        /// <summary>
        /// Deserializes xml markup from file into an EntityBase object
        /// </summary>
        /// <param name="fileName">string xml file to load and deserialize</param>
        /// <param name="obj">Output EntityBase object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool LoadFromFile(string fileName, System.Text.Encoding encoding, out T obj, out System.Exception exception)
        {
            exception = null;
            obj = default(T);
            try
            {
                obj = LoadFromFile(fileName, encoding);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool LoadFromFile(string fileName, out T obj, out System.Exception exception)
        {
            return LoadFromFile(fileName, Encoding.UTF8, out obj, out exception);
        }

        public static bool LoadFromFile(string fileName, out T obj)
        {
            System.Exception exception = null;
            return LoadFromFile(fileName, out obj, out exception);
        }

        public static T LoadFromFile(string fileName)
        {
            return LoadFromFile(fileName, Encoding.UTF8);
        }

        public static T LoadFromFile(string fileName, System.Text.Encoding encoding)
        {
            System.IO.FileStream file = null;
            System.IO.StreamReader sr = null;
            try
            {
                file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
                sr = new System.IO.StreamReader(file, encoding);
                string xmlString = sr.ReadToEnd();
                sr.Close();
                file.Close();
                return Deserialize(xmlString);
            }
            finally
            {
                if ((file != null))
                {
                    file.Dispose();
                }
                if ((sr != null))
                {
                    sr.Dispose();
                }
            }
        }
        #endregion
    }
    #endregion

    /// <summary>
    /// Poruka prema web servisu za zaprimanje racuna.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = false)]
    public partial class RacunZahtjev : EntityBase<RacunZahtjev>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ZaglavljeType zaglavljeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private RacunType racunField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string idField;

        /// <summary>
        /// RacunZahtjev class constructor
        /// </summary>
        public RacunZahtjev()
        {
            this.racunField = new RacunType();
            this.zaglavljeField = new ZaglavljeType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ZaglavljeType Zaglavlje
        {
            get
            {
                return this.zaglavljeField;
            }
            set
            {
                this.zaglavljeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public RacunType Racun
        {
            get
            {
                return this.racunField;
            }
            set
            {
                this.racunField = value;
            }
        }

        /// <summary>
        /// Atribut za potrebe digitalnog potpisa, u njega se stavlja referentni na koji se referencira digitalni potpis.
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = true)]
    public partial class ZaglavljeType : EntityBase<ZaglavljeType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string idPorukeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string datumVrijemeField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string IdPoruke
        {
            get
            {
                return this.idPorukeField;
            }
            set
            {
                this.idPorukeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string DatumVrijeme
        {
            get
            {
                return this.datumVrijemeField;
            }
            set
            {
                this.datumVrijemeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = true)]
    public partial class NaknadaType : EntityBase<NaknadaType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string nazivNField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string iznosNField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string NazivN
        {
            get
            {
                return this.nazivNField;
            }
            set
            {
                this.nazivNField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string IznosN
        {
            get
            {
                return this.iznosNField;
            }
            set
            {
                this.iznosNField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = true)]
    public partial class PorezOstaloType : EntityBase<PorezOstaloType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string nazivField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string stopaField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string osnovicaField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string iznosField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Naziv
        {
            get
            {
                return this.nazivField;
            }
            set
            {
                this.nazivField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Stopa
        {
            get
            {
                return this.stopaField;
            }
            set
            {
                this.stopaField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Osnovica
        {
            get
            {
                return this.osnovicaField;
            }
            set
            {
                this.osnovicaField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Iznos
        {
            get
            {
                return this.iznosField;
            }
            set
            {
                this.iznosField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = true)]
    public partial class PorezType : EntityBase<PorezType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string stopaField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string osnovicaField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string iznosField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Stopa
        {
            get
            {
                return this.stopaField;
            }
            set
            {
                this.stopaField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Osnovica
        {
            get
            {
                return this.osnovicaField;
            }
            set
            {
                this.osnovicaField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Iznos
        {
            get
            {
                return this.iznosField;
            }
            set
            {
                this.iznosField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = true)]
    public partial class BrojRacunaType : EntityBase<BrojRacunaType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string brOznRacField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string oznPosPrField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string oznNapUrField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string BrOznRac
        {
            get
            {
                return this.brOznRacField;
            }
            set
            {
                this.brOznRacField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string OznPosPr
        {
            get
            {
                return this.oznPosPrField;
            }
            set
            {
                this.oznPosPrField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string OznNapUr
        {
            get
            {
                return this.oznNapUrField;
            }
            set
            {
                this.oznNapUrField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = true)]
    public partial class RacunType : EntityBase<RacunType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string oibField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool uSustPdvField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string datVrijemeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private OznakaSlijednostiType oznSlijedField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private BrojRacunaType brRacField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<PorezType> pdvField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<PorezType> pnpField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<PorezOstaloType> ostaliPorField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string iznosOslobPdvField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string iznosMarzaField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string iznosNePodlOporField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<NaknadaType> naknadeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string iznosUkupnoField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private NacinPlacanjaType nacinPlacField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string oibOperField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string zastKodField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool nakDostField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string paragonBrRacField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string specNamjField;

        /// <summary>
        /// RacunType class constructor
        /// </summary>
        public RacunType()
        {
            this.naknadeField = new List<NaknadaType>();
            this.ostaliPorField = new List<PorezOstaloType>();
            this.pnpField = new List<PorezType>();
            this.pdvField = new List<PorezType>();
            this.brRacField = new BrojRacunaType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Oib
        {
            get
            {
                return this.oibField;
            }
            set
            {
                this.oibField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public bool USustPdv
        {
            get
            {
                return this.uSustPdvField;
            }
            set
            {
                this.uSustPdvField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string DatVrijeme
        {
            get
            {
                return this.datVrijemeField;
            }
            set
            {
                this.datVrijemeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public OznakaSlijednostiType OznSlijed
        {
            get
            {
                return this.oznSlijedField;
            }
            set
            {
                this.oznSlijedField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public BrojRacunaType BrRac
        {
            get
            {
                return this.brRacField;
            }
            set
            {
                this.brRacField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Porez", IsNullable = false)]
        public List<PorezType> Pdv
        {
            get
            {
                return this.pdvField;
            }
            set
            {
                this.pdvField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Porez", IsNullable = false)]
        public List<PorezType> Pnp
        {
            get
            {
                return this.pnpField;
            }
            set
            {
                this.pnpField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Porez", IsNullable = false)]
        public List<PorezOstaloType> OstaliPor
        {
            get
            {
                return this.ostaliPorField;
            }
            set
            {
                this.ostaliPorField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string IznosOslobPdv
        {
            get
            {
                return this.iznosOslobPdvField;
            }
            set
            {
                this.iznosOslobPdvField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string IznosMarza
        {
            get
            {
                return this.iznosMarzaField;
            }
            set
            {
                this.iznosMarzaField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public string IznosNePodlOpor
        {
            get
            {
                return this.iznosNePodlOporField;
            }
            set
            {
                this.iznosNePodlOporField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Naknada", IsNullable = false)]
        public List<NaknadaType> Naknade
        {
            get
            {
                return this.naknadeField;
            }
            set
            {
                this.naknadeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public string IznosUkupno
        {
            get
            {
                return this.iznosUkupnoField;
            }
            set
            {
                this.iznosUkupnoField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public NacinPlacanjaType NacinPlac
        {
            get
            {
                return this.nacinPlacField;
            }
            set
            {
                this.nacinPlacField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public string OibOper
        {
            get
            {
                return this.oibOperField;
            }
            set
            {
                this.oibOperField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public string ZastKod
        {
            get
            {
                return this.zastKodField;
            }
            set
            {
                this.zastKodField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public bool NakDost
        {
            get
            {
                return this.nakDostField;
            }
            set
            {
                this.nakDostField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public string ParagonBrRac
        {
            get
            {
                return this.paragonBrRacField;
            }
            set
            {
                this.paragonBrRacField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public string SpecNamj
        {
            get
            {
                return this.specNamjField;
            }
            set
            {
                this.specNamjField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    public enum OznakaSlijednostiType
    {

        /// <remarks/>
        N,

        /// <remarks/>
        P,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    public enum NacinPlacanjaType
    {

        /// <remarks/>
        G,

        /// <remarks/>
        K,

        /// <remarks/>
        C,

        /// <remarks/>
        T,

        /// <remarks/>
        O,
    }

    /// <summary>
    /// Odgovor servisa za zaprimanje racuna.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = false)]
    public partial class RacunOdgovor : EntityBase<RacunOdgovor>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ZaglavljeOdgovorType zaglavljeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string jirField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<GreskaType> greskeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string idField;

        /// <summary>
        /// RacunOdgovor class constructor
        /// </summary>
        public RacunOdgovor()
        {
            this.greskeField = new List<GreskaType>();
            this.zaglavljeField = new ZaglavljeOdgovorType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ZaglavljeOdgovorType Zaglavlje
        {
            get
            {
                return this.zaglavljeField;
            }
            set
            {
                this.zaglavljeField = value;
            }
        }

        /// <summary>
        /// Jedinstveni identifikator racuna.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string Jir
        {
            get
            {
                return this.jirField;
            }
            set
            {
                this.jirField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Greska", IsNullable = false)]
        public List<GreskaType> Greske
        {
            get
            {
                return this.greskeField;
            }
            set
            {
                this.greskeField = value;
            }
        }

        /// <summary>
        /// Atribut za potrebe digitalnog potpisa, u njega se stavlja referentni na koji se referencira digitalni potpis.
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = true)]
    public partial class ZaglavljeOdgovorType : EntityBase<ZaglavljeOdgovorType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string idPorukeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string datumVrijemeField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string IdPoruke
        {
            get
            {
                return this.idPorukeField;
            }
            set
            {
                this.idPorukeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string DatumVrijeme
        {
            get
            {
                return this.datumVrijemeField;
            }
            set
            {
                this.datumVrijemeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = true)]
    public partial class GreskaType : EntityBase<GreskaType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string sifraGreskeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string porukaGreskeField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string SifraGreske
        {
            get
            {
                return this.sifraGreskeField;
            }
            set
            {
                this.sifraGreskeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string PorukaGreske
        {
            get
            {
                return this.porukaGreskeField;
            }
            set
            {
                this.porukaGreskeField = value;
            }
        }
    }

    /// <summary>
    /// Poruka prema web servisu za zaprimanje podataka o poslovnom prostoru.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = false)]
    public partial class PoslovniProstorZahtjev : EntityBase<PoslovniProstorZahtjev>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ZaglavljeType zaglavljeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private PoslovniProstorType poslovniProstorField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string idField;

        /// <summary>
        /// PoslovniProstorZahtjev class constructor
        /// </summary>
        public PoslovniProstorZahtjev()
        {
            this.poslovniProstorField = new PoslovniProstorType();
            this.zaglavljeField = new ZaglavljeType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ZaglavljeType Zaglavlje
        {
            get
            {
                return this.zaglavljeField;
            }
            set
            {
                this.zaglavljeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public PoslovniProstorType PoslovniProstor
        {
            get
            {
                return this.poslovniProstorField;
            }
            set
            {
                this.poslovniProstorField = value;
            }
        }

        /// <summary>
        /// Atribut za potrebe digitalnog potpisa, u njega se stavlja referentni na koji se referencira digitalni potpis.
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = true)]
    public partial class PoslovniProstorType : EntityBase<PoslovniProstorType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string oibField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string oznPoslProstoraField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private AdresniPodatakType adresniPodatakField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string radnoVrijemeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string datumPocetkaPrimjeneField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private OznakaZatvaranjaType oznakaZatvaranjaField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private bool oznakaZatvaranjaFieldSpecified;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string specNamjField;

        /// <summary>
        /// PoslovniProstorType class constructor
        /// </summary>
        public PoslovniProstorType()
        {
            this.adresniPodatakField = new AdresniPodatakType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Oib
        {
            get
            {
                return this.oibField;
            }
            set
            {
                this.oibField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string OznPoslProstora
        {
            get
            {
                return this.oznPoslProstoraField;
            }
            set
            {
                this.oznPoslProstoraField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public AdresniPodatakType AdresniPodatak
        {
            get
            {
                return this.adresniPodatakField;
            }
            set
            {
                this.adresniPodatakField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string RadnoVrijeme
        {
            get
            {
                return this.radnoVrijemeField;
            }
            set
            {
                this.radnoVrijemeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string DatumPocetkaPrimjene
        {
            get
            {
                return this.datumPocetkaPrimjeneField;
            }
            set
            {
                this.datumPocetkaPrimjeneField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public OznakaZatvaranjaType OznakaZatvaranja
        {
            get
            {
                return this.oznakaZatvaranjaField;
            }
            set
            {
                this.oznakaZatvaranjaField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OznakaZatvaranjaSpecified
        {
            get
            {
                return this.oznakaZatvaranjaFieldSpecified;
            }
            set
            {
                this.oznakaZatvaranjaFieldSpecified = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string SpecNamj
        {
            get
            {
                return this.specNamjField;
            }
            set
            {
                this.specNamjField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = true)]
    public partial class AdresniPodatakType : EntityBase<AdresniPodatakType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private object itemField;

        [System.Xml.Serialization.XmlElementAttribute("Adresa", typeof(AdresaType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("OstaliTipoviPP", typeof(string), Order = 0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = true)]
    public partial class AdresaType : EntityBase<AdresaType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string ulicaField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string kucniBrojField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string kucniBrojDodatakField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string brojPosteField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string naseljeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string opcinaField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Ulica
        {
            get
            {
                return this.ulicaField;
            }
            set
            {
                this.ulicaField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string KucniBroj
        {
            get
            {
                return this.kucniBrojField;
            }
            set
            {
                this.kucniBrojField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string KucniBrojDodatak
        {
            get
            {
                return this.kucniBrojDodatakField;
            }
            set
            {
                this.kucniBrojDodatakField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string BrojPoste
        {
            get
            {
                return this.brojPosteField;
            }
            set
            {
                this.brojPosteField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string Naselje
        {
            get
            {
                return this.naseljeField;
            }
            set
            {
                this.naseljeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string Opcina
        {
            get
            {
                return this.opcinaField;
            }
            set
            {
                this.opcinaField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    public enum OznakaZatvaranjaType
    {

        /// <remarks/>
        Z,
    }

    /// <summary>
    /// Odgovor servisa za zaprimanje podataka o poslovnom prostoru.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = false)]
    public partial class PoslovniProstorOdgovor : EntityBase<PoslovniProstorOdgovor>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private ZaglavljeOdgovorType zaglavljeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<GreskaType> greskeField;

        [EditorBrowsable(EditorBrowsableState.Never)]
        private string idField;

        /// <summary>
        /// PoslovniProstorOdgovor class constructor
        /// </summary>
        public PoslovniProstorOdgovor()
        {
            this.greskeField = new List<GreskaType>();
            this.zaglavljeField = new ZaglavljeOdgovorType();
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ZaglavljeOdgovorType Zaglavlje
        {
            get
            {
                return this.zaglavljeField;
            }
            set
            {
                this.zaglavljeField = value;
            }
        }

        [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Greska", IsNullable = false)]
        public List<GreskaType> Greske
        {
            get
            {
                return this.greskeField;
            }
            set
            {
                this.greskeField = value;
            }
        }

        /// <summary>
        /// Atribut za potrebe digitalnog potpisa, u njega se stavlja referentni na koji se referencira digitalni potpis.
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = true)]
    public partial class GreskeType : EntityBase<GreskeType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<GreskaType> greskaField;

        /// <summary>
        /// GreskeType class constructor
        /// </summary>
        public GreskeType()
        {
            this.greskaField = new List<GreskaType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("Greska", Order = 0)]
        public List<GreskaType> Greska
        {
            get
            {
                return this.greskaField;
            }
            set
            {
                this.greskaField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = true)]
    public partial class NaknadeType : EntityBase<NaknadeType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<NaknadaType> naknadaField;

        /// <summary>
        /// NaknadeType class constructor
        /// </summary>
        public NaknadeType()
        {
            this.naknadaField = new List<NaknadaType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("Naknada", Order = 0)]
        public List<NaknadaType> Naknada
        {
            get
            {
                return this.naknadaField;
            }
            set
            {
                this.naknadaField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = true)]
    public partial class OstaliPoreziType : EntityBase<OstaliPoreziType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<PorezOstaloType> porezField;

        /// <summary>
        /// OstaliPoreziType class constructor
        /// </summary>
        public OstaliPoreziType()
        {
            this.porezField = new List<PorezOstaloType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("Porez", Order = 0)]
        public List<PorezOstaloType> Porez
        {
            get
            {
                return this.porezField;
            }
            set
            {
                this.porezField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = true)]
    public partial class PorezNaPotrosnjuType : EntityBase<PorezNaPotrosnjuType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<PorezType> porezField;

        /// <summary>
        /// PorezNaPotrosnjuType class constructor
        /// </summary>
        public PorezNaPotrosnjuType()
        {
            this.porezField = new List<PorezType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("Porez", Order = 0)]
        public List<PorezType> Porez
        {
            get
            {
                return this.porezField;
            }
            set
            {
                this.porezField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.apis-it.hr/fin/2012/types/f73", IsNullable = true)]
    public partial class PdvType : EntityBase<PdvType>
    {

        [EditorBrowsable(EditorBrowsableState.Never)]
        private List<PorezType> porezField;

        /// <summary>
        /// PdvType class constructor
        /// </summary>
        public PdvType()
        {
            this.porezField = new List<PorezType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("Porez", Order = 0)]
        public List<PorezType> Porez
        {
            get
            {
                return this.porezField;
            }
            set
            {
                this.porezField = value;
            }
        }
    }
}
